export default {
  NEW_PAGE: "NEW_PAGE",
  NEXT_FILMS_PAGE: "NEXT_FILMS_PAGE",
  PREVIOUS_FILMS_PAGE: "PREVIOUS_FILMS_PAGE",
  MINIMUM_NUM_PAGES: "MINIMUM_NUM_PAGES",
  MESSAGE_ALERT: "MESSAGE_ALERT",
  SEARCH_TEXT: "SEARCH_TEXT ",
  TOTAL_NUM_PAGES: "TOTAL_NUM_PAGES",
};
