export default {
  SelectedFilm: {
    tv: {
      adult: false,
      backdrop_path: "/bBziqQXj6ELvVCpPfxGM9OWJpWa.jpg",
      created_by: [
        {
          id: 52779,
          credit_id: "5cd9ce24c3a3681443c212ed",
          name: "Ryan Murphy",
          gender: 2,
          profile_path: "/uPojf0hEIpud1huRC9NY7R55OSy.jpg",
        },
        {
          id: 202100,
          credit_id: "5cd9ce34c3a36877cfc3f54f",
          name: "Tim Minear",
          gender: 2,
          profile_path: "/zOnOJmM0sShVbLgW2jB0j0r6D6U.jpg",
        },
        {
          id: 1224030,
          credit_id: "5cd9ce2c9251413606ce519a",
          name: "Brad Falchuk",
          gender: 2,
          profile_path: "/kVMTpVi2I9UhlcJdBUWcq744Lgg.jpg",
        },
      ],
      episode_run_time: [43],
      first_air_date: "2020-01-19",
      genres: [
        { id: 18, name: "Drama" },
        { id: 10759, name: "Action & Adventure" },
        { id: 80, name: "Crimen" },
      ],
      homepage: "https://www.fox.com/9-1-1-lone-star/",
      id: 89393,
      in_production: true,
      languages: ["en"],
      last_air_date: "2022-03-21",
      last_episode_to_air: {
        air_date: "2022-03-21",
        episode_number: 11,
        id: 3511820,
        name: "",
        overview: "",
        production_code: "",
        season_number: 3,
        still_path: "/Vq5IfJgniNHLlmFeSgJiuSBJjG.jpg",
        vote_average: 10.0,
        vote_count: 1,
      },
      name: "9-1-1: Lone Star",
      next_episode_to_air: {
        air_date: "2022-03-28",
        episode_number: 12,
        id: 3521110,
        name: "",
        overview: "",
        production_code: "",
        season_number: 3,
        still_path: "/3yQZuoh8za3qgyfxGgvrcdK4lZd.jpg",
        vote_average: 0.0,
        vote_count: 0,
      },
      networks: [
        {
          name: "FOX",
          id: 19,
          logo_path: "/1DSpHrWyOORkL9N2QHX7Adt31mQ.png",
          origin_country: "US",
        },
      ],
      number_of_episodes: 37,
      number_of_seasons: 3,
      origin_country: ["US"],
      original_language: "en",
      original_name: "9-1-1: Lone Star",
      overview:
        "Este spin-off de 9-1-1, se centra en Owen Strand, un sofisticado bombero de Nueva York que se muda a Austin, Texas, con su hijo. En esta nueva vida tiene que encontrar el equilibrio entre salvar a los más vulnerables o resolver sus propios problemas personales.",
      popularity: 241.841,
      poster_path: "/fyW4ex9owJcUU9VNel64l1tvXgF.jpg",
      production_companies: [
        {
          id: 68682,
          logo_path: "/x4htMipi2e3QMQuyeLhrwlpxgKf.png",
          name: "Brad Falchuk Teley-vision",
          origin_country: "US",
        },
        {
          id: 19328,
          logo_path: "/2AdkrU1av4fDGw0Zaf68XH4YcqC.png",
          name: "Ryan Murphy Productions",
          origin_country: "US",
        },
        {
          id: 21659,
          logo_path: "/uJhjhEJEPDoCSSOci44tYoe5BjZ.png",
          name: "20th Television",
          origin_country: "US",
        },
      ],
      production_countries: [
        { iso_3166_1: "US", name: "United States of America" },
      ],
      seasons: [
        {
          air_date: "2020-01-19",
          episode_count: 10,
          id: 124243,
          name: "Temporada 1",
          overview: "",
          poster_path: "/cKZ15eWIPj11oVL7kFvScAbhuxx.jpg",
          season_number: 1,
        },
        {
          air_date: "2021-01-18",
          episode_count: 14,
          id: 168577,
          name: "Temporada 2",
          overview: "",
          poster_path: "/mrzE6bXc8g9NQd8IBKB25louWq8.jpg",
          season_number: 2,
        },
        {
          air_date: "2022-01-03",
          episode_count: 13,
          id: 213518,
          name: "Temporada 3",
          overview: "",
          poster_path: "/fyW4ex9owJcUU9VNel64l1tvXgF.jpg",
          season_number: 3,
        },
      ],
      spoken_languages: [
        { english_name: "English", iso_639_1: "en", name: "English" },
      ],
      status: "Returning Series",
      tagline: "",
      type: "Scripted",
      vote_average: 8.0,
      vote_count: 691,
    },
    movie: {
      adult: false,
      backdrop_path: "/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg",
      belongs_to_collection: {
        id: 2883,
        name: "Kill Bill - Colección",
        poster_path: "/3g6ymX5cGyzXejM8NQXQFzLMFJe.jpg",
        backdrop_path: "/oCLKNACMNrEf4T1EP6BpMXDl5m1.jpg",
      },
      budget: 30000000,
      genres: [
        { id: 28, name: "Acción" },
        { id: 80, name: "Crimen" },
      ],
      homepage: "http://www.miramax.com/movie/kill-bill-volume-1",
      id: 24,
      imdb_id: "tt0266697",
      original_language: "en",
      original_title: "Kill Bill: Vol. 1",
      overview:
        "Uma Thurman es una asesina que, el día de su boda, es atacada por los miembros de la banda de su jefe, Bill (David Carradine). Logra sobrevivir al ataque, aunque queda en coma. Cinco años después despierta con un trozo de metal en la cabeza y un gran deseo de venganza en su corazón.",
      popularity: 49.887,
      poster_path: "/lfj709InbmljVqAXgUk2qjnujNN.jpg",
      production_companies: [
        {
          id: 14,
          logo_path: "/m6AHu84oZQxvq7n1rsvMNJIAsMu.png",
          name: "Miramax",
          origin_country: "US",
        },
        {
          id: 59,
          logo_path: "/yH7OMeSxhfP0AVM6iT0rsF3F4ZC.png",
          name: "A Band Apart",
          origin_country: "US",
        },
      ],
      production_countries: [
        { iso_3166_1: "US", name: "United States of America" },
      ],
      release_date: "2003-10-10",
      revenue: 180899265,
      runtime: 111,
      spoken_languages: [
        { english_name: "English", iso_639_1: "en", name: "English" },
        { english_name: "Japanese", iso_639_1: "ja", name: "日本語" },
        { english_name: "French", iso_639_1: "fr", name: "Français" },
      ],
      status: "Released",
      tagline: "La sangrienta historia de una venganza",
      title: "Kill Bill: Volumen 1",
      video: false,
      vote_average: 8.0,
      vote_count: 14422,
    },
  },

  Films: {
    page_1: [
      {
        backdrop_path: "/iIm3WJ55weRMNPqnBJPMRgw9m8U.jpg",
        first_air_date: "2018-01-03",
        genre_ids: [18, 80, 10759],
        id: 75219,
        media_type: "tv",
        name: "9-1-1",
        origin_country: ["US"],
        original_language: "en",
        original_name: "9-1-1",
        overview:
          "Drama basado en hechos reales que explora la ajetreada profesión y vida del personal que opera detrás de la línea de emergencia 911. A través de ella, policías, paramédicos y bomberos reciben llamadas de urgencias diarias por las que rápidamente deben acudir y poner en riesgo su vida para salvar la de otros.",
        popularity: 391.381,
        poster_path: "/qJWsXzGAy65bUgsYYuk7jzOpuvx.jpg",
        vote_average: 8.2,
        vote_count: 1733,
      },
      {
        backdrop_path: "/bBziqQXj6ELvVCpPfxGM9OWJpWa.jpg",
        first_air_date: "2020-01-19",
        genre_ids: [18, 10759, 80],
        id: 89393,
        media_type: "tv",
        name: "9-1-1: Lone Star",
        origin_country: ["US"],
        original_language: "en",
        original_name: "9-1-1: Lone Star",
        overview:
          "Este spin-off de 9-1-1, se centra en Owen Strand, un sofisticado bombero de Nueva York que se muda a Austin, Texas, con su hijo. En esta nueva vida tiene que encontrar el equilibrio entre salvar a los más vulnerables o resolver sus propios problemas personales.",
        popularity: 338.577,
        poster_path: "/fyW4ex9owJcUU9VNel64l1tvXgF.jpg",
        vote_average: 8,
        vote_count: 691,
      },
      {
        backdrop_path: "/li9SZBpVzJz81ouqifVuH5C7Nod.jpg",
        first_air_date: "1997-07-27",
        genre_ids: [10765, 10759, 9648],
        id: 4629,
        media_type: "tv",
        name: "Stargate SG-1",
        origin_country: ["US", "CA"],
        original_language: "en",
        original_name: "Stargate SG-1",
        overview:
          "Stargate SG-1 es una serie televisiva estadounidense derivada del largometraje de ciencia ficción 'Stargate: Puerta a las Estrellas' (1994). Producida por los estudios Metro Goldwyn Mayer. Esta serie se centra en las vivencias y aventuras de un equipo de militares y científicos miembros de un proyecto ultra-secreto de las Fuerzas Aéreas de los Estados Unidos, que utiliza un ingenio extraterrestre (Stargate) para desplazarse a otros planetas de manera casi instantánea.",
        popularity: 255.106,
        poster_path: "/747src7yfYpPldaYi7c5IXjxDko.jpg",
        vote_average: 8.2,
        vote_count: 1101,
      },
      {
        backdrop_path: "/aIRgBlrM0qKvc76nVcScWVmg8ht.jpg",
        first_air_date: "2022-03-23",
        genre_ids: [18],
        id: 137872,
        media_type: "tv",
        name: "Soundtrack #1",
        origin_country: ["KR"],
        original_language: "ko",
        original_name: "Soundtrack #1",
        overview:
          "Han Sun-Woo es un fotógrafo novato. No habla mucho, pero es un hombre amable y afectuoso. Es amigo de Lee Eun-Soo. Han sido amigos cercanos durante 20 años. Mientras tanto, Lee Eun-Soo trabaja como letrista para ganarse la vida. Ella tiene una personalidad honesta y brillante. Por una razón, Han Sun-Woo y Lee Eun-Soo comienzan a vivir juntos en la misma casa durante 2 semanas. Permaneciendo juntos, su relación se desarrolla románticamente.",
        popularity: 25.394,
        poster_path: "/gSsbkYG5AYnPJyA1LuNfCMx2iYe.jpg",
        vote_average: 8.4,
        vote_count: 5,
      },
      {
        backdrop_path: "/vMci8LZG3zY9oXIhGXzkFOg0Nu7.jpg",
        first_air_date: "2019-03-08",
        genre_ids: [99],
        id: 87083,
        media_type: "tv",
        name: "Formula 1: Drive to Survive",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Formula 1: Drive to Survive",
        overview:
          "Serie documental sobre el mundo de la Fórmula 1 de los productores de Senna y Amy. Se centrará en la vida personal de los corredores, sus familias, amigos y el mundo que hay detrás de las carreras.",
        popularity: 84.354,
        poster_path: "/60g35FPacj9cA0Sq8j48ZtIBBfL.jpg",
        vote_average: 8.4,
        vote_count: 240,
      },
      {
        adult: false,
        backdrop_path: "/palbhPOSYf2g1p18vWd91dDhZLM.jpg",
        genre_ids: [28, 27, 878],
        id: 485811,
        media_type: "movie",
        original_language: "en",
        original_title: "Redcon-1",
        overview:
          "Cuando los zombis comienzan a tomar el control del mundo se convierten en versiones malignas de sus personalidades pasadas pero adquiriendo cualquier habilidad de combate previa que tuviera la persona mejorada con capacidades superhumanas… esto hace su erradicación casi imposible. En este infierno existe una unidad de fuerzas especiales que son asignados a una misión suicida con el objetivo de rescatar a un científico atrapado en una ciudad dirigida por los muertos vivientes",
        popularity: 31.77,
        poster_path: "/nJMIcYfM8ktbb55T7dwAgzYoFWw.jpg",
        release_date: "2018-09-07",
        title: "Apocalipsis zombie",
        video: false,
        vote_average: 5.6,
        vote_count: 200,
      },
      {
        adult: false,
        backdrop_path: "/tFlSDoWQsAZ2qjICKzfP5Yw6zM5.jpg",
        genre_ids: [878, 12, 53],
        id: 131631,
        media_type: "movie",
        original_language: "en",
        original_title: "The Hunger Games: Mockingjay - Part 1",
        overview:
          'Katniss Everdeen se encuentra en el Distrito 13 después de destrozar los Juegos para siempre. Bajo el liderazgo de la comandante Coin y el consejo de sus amigos más leales, Katniss extiende sus alas mientras lucha por salvar a Peeta Mellark y a una nación alentada por su valentía... Tercera y última entrega de la saga literaria "Los juegos del hambre" de Suzanne Collins, que se divide en dos películas.',
        popularity: 178.64,
        poster_path: "/obDqU7EsRI39VknQg4fDeqQf8Cq.jpg",
        release_date: "2014-11-19",
        title: "Los juegos del hambre: Sinsajo. Parte 1",
        video: false,
        vote_average: 6.8,
        vote_count: 13426,
      },
      {
        adult: false,
        backdrop_path: "/3eQnD9CIUerbXbgtFE1zJNvEVVo.jpg",
        genre_ids: [10751, 16, 35],
        id: 11430,
        media_type: "movie",
        original_language: "en",
        original_title: "The Lion King 1½",
        overview:
          "La diversión reina en esta nueva película en al que Timón y su simpático amigo Pumba son los grandes héroes de la Sabana. El Rey León 3 nos traslada al pasado, antes de que comenzase la historia de Simba, e incluso mucho más atrás. En esta nueva comedia de aventuras, Timón y Pumba te descubrirán sus orígenes, cuándo se conocieron y cómo ayudaron a Simba a salvar el Seregeti. Su historia incluye algunos de los grandes momentos de El Rey León, que ahora resultarán un poco diferentes desde su punto de vista. Por ejemplo, os sorprenderá conocer la verdad sobre cómo se desarrolló el trascendental momento en el que Simba fue presentado al reino animal.",
        popularity: 91.122,
        poster_path: "/x2SAEOXURbKDgKfdHdZ49VhPGrB.jpg",
        release_date: "2004-02-06",
        title: "El rey león 3: Hakuna Matata",
        video: false,
        vote_average: 6.6,
        vote_count: 2492,
      },
      {
        adult: false,
        backdrop_path: "/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg",
        genre_ids: [28, 80],
        id: 24,
        media_type: "movie",
        original_language: "en",
        original_title: "Kill Bill: Vol. 1",
        overview:
          "Uma Thurman es una asesina que, el día de su boda, es atacada por los miembros de la banda de su jefe, Bill (David Carradine). Logra sobrevivir al ataque, aunque queda en coma. Cinco años después despierta con un trozo de metal en la cabeza y un gran deseo de venganza en su corazón.",
        popularity: 49.984,
        poster_path: "/lfj709InbmljVqAXgUk2qjnujNN.jpg",
        release_date: "2003-10-10",
        title: "Kill Bill: Volumen 1",
        video: false,
        vote_average: 8,
        vote_count: 14422,
      },
      {
        adult: false,
        backdrop_path: "/fXRXpzxUApE3OuXhIqsdavQjCVa.jpg",
        genre_ids: [12, 14],
        id: 12444,
        media_type: "movie",
        original_language: "en",
        original_title: "Harry Potter and the Deathly Hallows: Part 1",
        overview:
          "Una tarea casi imposible cae sobre los hombros de Harry: deberá encontrar y destruir los horrocruxes restantes para dar fin al reinado de Lord Voldemort. En el episodio final de la saga, el hechicero de 17 años parte junto con sus amigos Hermione Granger y Ron Weasley en un peligroso viaje por Inglaterra para encontrar los objetos que contienen los fragmentos del alma del Señor Tenebroso, los cuales garantizan su longevidad. Pero el camino no será fácil pues el lado oscuro adquiere más poder con cada minuto que pasa y las lealtades serán puestas a prueba. Harry deberá usar todos los conocimientos que gracias a Dumbledore ha adquirido sobre su enemigo para poder encontrar la forma de sobrevivir a esta última aventura.",
        popularity: 239.517,
        poster_path: "/fYyoJ4Yadk0MCBHZPFrgvMDl50o.jpg",
        release_date: "2010-10-17",
        title: "Harry Potter y las Reliquias de la Muerte - Parte 1",
        video: false,
        vote_average: 7.8,
        vote_count: 15811,
      },
      {
        adult: false,
        backdrop_path: "/exH0qO1tzG2a6LHeyzaWI2gZvfi.jpg",
        genre_ids: [12, 14, 10749],
        id: 50619,
        media_type: "movie",
        original_language: "en",
        original_title: "The Twilight Saga: Breaking Dawn - Part 1",
        overview:
          "El amor que Edward y Bella sienten el uno por el otro se sella con la celebración de una gran ceremonia organizada por Alice. Durante la luna de miel, los recién casados tienen relaciones sexuales y Bella queda embarazada. El rápido crecimiento del feto, mitad humano mitad vampiro, afecta gravemente a su salud, llevándola al borde de la muerte...",
        popularity: 176.623,
        poster_path: "/27WlKKz9f3vMr6JvSf0LDBVdtaZ.jpg",
        release_date: "2011-11-16",
        title: "La saga Crepúsculo:  Amanecer - Parte 1",
        video: false,
        vote_average: 6.2,
        vote_count: 7457,
      },
      {
        backdrop_path: "/pj7unJRCTLzwu8TThn4zrqiFi79.jpg",
        first_air_date: "2021-08-29",
        genre_ids: [],
        id: 129396,
        media_type: "tv",
        name: "1. MISE",
        origin_country: ["CZ"],
        original_language: "cs",
        original_name: "1. MISE",
        overview: "",
        popularity: 12.074,
        poster_path: "/lCepPCDldLhX8wKkfapYChf7oww.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        backdrop_path: "/3SIQZv4oPcbvo1ieidOTTO5BIz3.jpg",
        first_air_date: "2019-07-30",
        genre_ids: [10766],
        id: 91242,
        media_type: "tv",
        name: "Preso No. 1",
        origin_country: ["US"],
        original_language: "es",
        original_name: "Preso No. 1",
        overview:
          "La historia de un joven campesino que se convierte en presidente de México. Pero una falsa acusación, lo lleva a prisión. Ahora deberá luchar por su vida y por salir en libertad, comprobar su inocencia y hacer pagar a quienes conspiraron para hundirlo.",
        popularity: 14.658,
        poster_path: "/8tTpbFJzcjqLZSiPeoeINpaPG7d.jpg",
        vote_average: 7.2,
        vote_count: 124,
      },
      {
        backdrop_path: "/6pMgfh0j9FOwre6kEtehFUykKZ2.jpg",
        first_air_date: "2005-10-11",
        genre_ids: [18, 10751],
        id: 6484,
        media_type: "tv",
        name: "1 Rittoru No Namida",
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "１リットルの涙",
        overview:
          "Ikeuchi Aya es una chica ordinaria de 15 años de edad, hija de una  familia que trabaja en una tienda de tofu y que pronto entrará a la  preparatoria. Sin embargo, cosas extrañas le han estado ocurriendo a Aya  últimamente. Se ha estado cayendo muy seguido y camina de manera muy  extraña. Su madre, Shioka, lleva a Aya a ver a un médico y él le informa  que Aya tiene una degeneración espinocerebral. Es una terrible  enfermedad incurable en la cual el cerebelo gradualmente se va  deteriorando hasta el punto en que la persona ya no podrá caminar,  hablar, escribir o comer de manera normal pero que no afecta a la mente.  Al igual que en su vida existen personas que le hagan daño existira  personas que la apoyaran como Haruto, que la ayuda en los momentos de  dolor y le da el aliento que necesite. ¿Cómo terminará esta historia?",
        popularity: 20.422,
        poster_path: "/nwPp8ClNZAFl7Mm4H1GrQHF23az.jpg",
        vote_average: 8.4,
        vote_count: 87,
      },
      {
        backdrop_path: "/a7EzSW0Oda9jgIccbuX8B94CuJa.jpg",
        first_air_date: "2021-09-20",
        genre_ids: [18, 10751, 10766],
        id: 138242,
        media_type: "tv",
        name: "La 1-5/18",
        origin_country: ["AR"],
        original_language: "es",
        original_name: "La 1-5/18",
        overview:
          "La historia transcurre en la villa 1-5/18, recientemente bautizada como «La Peñaloza», donde conviven vecinos de distintas edades y diversidad sexual que, a pesar de estar privados de algunos derechos y de atravesar la carencia, siempre están dispuestos a colaborar y a luchar por el bienestar de toda la comunidad. Lola (Agustina Cherri) y Rita (Lali González) manejan un comedor comunitario, distribuyendo donaciones y ayudando a quien lo necesita.",
        popularity: 29.371,
        poster_path: "/mPRjUpafwAXkc6otZR2Kbobk4Aa.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        backdrop_path: "/deSSvVnRiZQSrUSBwPpT6m67aA1.jpg",
        first_air_date: "2012-01-05",
        genre_ids: [35],
        id: 48268,
        media_type: "tv",
        name: "1 Erkek 1 Kadın",
        origin_country: ["TR"],
        original_language: "tr",
        original_name: "1 Erkek 1 Kadın",
        overview: "",
        popularity: 5.947,
        poster_path: "/aL5MhgTj3zxLtN2chrvWmI36S8Y.jpg",
        vote_average: 7.6,
        vote_count: 5,
      },
      {
        adult: false,
        backdrop_path: "/1YaG52CwGY3pKh76OBlwX0ymncg.jpg",
        genre_ids: [878, 28, 16, 9648],
        id: 123025,
        media_type: "movie",
        original_language: "en",
        original_title: "Batman: The Dark Knight Returns, Part 1",
        overview:
          'Bruce Wayne hace más de diez años que abandonó la capa de murciélago atormentado por la muerte de Robín. La ciudad de Gotham esta hundida en la decadencia y la anarquía. Ahora, cuando su ciudad más lo necesita, El Regreso del Caballero Oscuro es un resplandor de gloria. Apoyado por Carrie Kelly, una adolescente que asumirá el puesto de Robin, el murciélago sale nuevamente a la calle para poner fi n a la amenaza de pandillas mutantes que han invadido la ciudad. Y después estará frente a frente contra sus dos grandes enemigos, el Joker y Dos Caras. Primera parte de la adaptación del aclamado cómic de Frank Miller "El retorno del señor de la noche".',
        popularity: 64.172,
        poster_path: "/yplFdLSePwRdVeiw3xfnumeTvsH.jpg",
        release_date: "2012-08-21",
        title: "Batman: El regreso del Caballero Oscuro, Parte 1",
        video: false,
        vote_average: 7.8,
        vote_count: 1206,
      },
      {
        adult: false,
        backdrop_path: "/cnFn8iShHVnu0K4gGGKuII3JPJa.jpg",
        genre_ids: [28, 18, 53],
        id: 10394,
        media_type: "movie",
        original_language: "en",
        original_title: "Gangster No. 1",
        overview:
          "Historia de un gángster del East End de Londres a lo largo de treinta años, desde sus comienzos en el Soho londinense hasta nuestros días.",
        popularity: 11.224,
        poster_path: "/gIQUVBPM9ehCelrjQEdKX29AaCT.jpg",
        release_date: "2000-06-09",
        title: "Gangster No. 1",
        video: false,
        vote_average: 6.5,
        vote_count: 149,
      },
      {
        adult: false,
        backdrop_path: "/aw0EeseSr10dVUuY6Aiv6HhP8UW.jpg",
        genre_ids: [28, 80, 27],
        id: 9696,
        media_type: "movie",
        original_language: "ja",
        original_title: "殺し屋1",
        overview:
          "Un conocido jefe de la Yakuza (la mafia japonesa) desaparece junto con un botín de 100 millones de yenes. Su mano derecha, el sanguinario y masoquista Kakihara, y el resto del clan, emprenden su búsqueda, ya que no creen que se haya fugado. Para encontrarlo utilizarán todos los métodos que consideren oportunos, ya sea torturando o matando. Así, Kakihara consigue averiguar que lo que pensaban que era una desaparición, es en realidad un asesinato, cometido por un hombre llamado Ichi, un esquizofrénico que cuando pierde el control puede hacer picadillo, literalmente, a cualquiera. Con esto, quiere resarcirse de los traumas de la infancia, aunque lo que consigue es lo contrario. Pero Ichi no esta sólo en esta lucha, le acompañan unos repudiados del clan, destacando a Jijii, que es la cabeza del grupo y quien incita al caos que se organiza.",
        popularity: 25.462,
        poster_path: "/gtqkEgS7fhvgKmSCt9EqTdQt6t9.jpg",
        release_date: "2001-12-22",
        title: "Ichi the Killer",
        video: false,
        vote_average: 7.1,
        vote_count: 677,
      },
      {
        adult: false,
        backdrop_path: "/dlq3GoejDFL1AfLeoOnarf6bGUW.jpg",
        genre_ids: [28, 35, 10749],
        id: 249772,
        media_type: "movie",
        original_language: "te",
        original_title: "1 - నేనొక్కడినే",
        overview: "",
        popularity: 4.365,
        poster_path: "/dYpqpA7BsDHeyAGs9AAEPhZmbck.jpg",
        release_date: "2014-01-10",
        title: "1 - నేనొక్కడినే",
        video: false,
        vote_average: 6.3,
        vote_count: 55,
      },
    ],
    page_2: [
      {
        adult: false,
        backdrop_path: "/cnFn8iShHVnu0K4gGGKuII3JPJa.jpg",
        genre_ids: [28, 18, 53],
        id: 10394,
        media_type: "movie",
        original_language: "en",
        original_title: "Gangster No. 1",
        overview:
          "Historia de un gángster del East End de Londres a lo largo de treinta años, desde sus comienzos en el Soho londinense hasta nuestros días.",
        popularity: 10.942,
        poster_path: "/gIQUVBPM9ehCelrjQEdKX29AaCT.jpg",
        release_date: "2000-06-09",
        title: "Gangster No. 1",
        video: false,
        vote_average: 6.5,
        vote_count: 149,
      },
      {
        adult: false,
        backdrop_path: "/kmbRz29SrAAOjNH0hsnBYOddjNN.jpg",
        genre_ids: [18, 10749],
        id: 10068,
        media_type: "movie",
        original_language: "en",
        original_title: "Nine 1/2 Weeks",
        overview:
          "Elizabeth, una bella marchante de arte, entabla relación con John, un broker de Wall Street. Tras unos inicios apasionados, la pareja se embarcará, por deseo de él, en una serie de juegos eróticos cada vez más extraños que confundirán a Elizabeth, pues ella le ama pero desconoce los verdaderos sentimientos de John.",
        popularity: 19.034,
        poster_path: "/oQDTKI8TYZ90lzVRNB8mk7UFe6b.jpg",
        release_date: "1986-02-09",
        title: "9 semanas y media",
        video: false,
        vote_average: 6.1,
        vote_count: 723,
      },
      {
        adult: false,
        backdrop_path: "/nomgM5XsdnkxbdinE2OjdxbXlpq.jpg",
        genre_ids: [28, 18],
        id: 852605,
        media_type: "movie",
        original_language: "en",
        original_title: "WWE WrestleMania 38 (Night 1)",
        overview: "",
        popularity: 28.813,
        poster_path: "/52bCuiV4ArhtFmRsXEN8JKANDpP.jpg",
        release_date: "2022-04-02",
        title: "WWE WrestleMania 38 (Night 1)",
        video: true,
        vote_average: 0,
        vote_count: 0,
      },
      {
        backdrop_path: null,
        first_air_date: "1977-09-01",
        genre_ids: [80],
        id: 40610,
        media_type: "tv",
        name: "Polizeiinspektion 1",
        origin_country: ["DE"],
        original_language: "de",
        original_name: "Polizeiinspektion 1",
        overview: "",
        popularity: 6.047,
        poster_path: "/5RbxVNsEfKkHDWKVZlJXxRkx58x.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/aw0EeseSr10dVUuY6Aiv6HhP8UW.jpg",
        genre_ids: [28, 80, 27],
        id: 9696,
        media_type: "movie",
        original_language: "ja",
        original_title: "殺し屋1",
        overview:
          "Un conocido jefe de la Yakuza (la mafia japonesa) desaparece junto con un botín de 100 millones de yenes. Su mano derecha, el sanguinario y masoquista Kakihara, y el resto del clan, emprenden su búsqueda, ya que no creen que se haya fugado. Para encontrarlo utilizarán todos los métodos que consideren oportunos, ya sea torturando o matando. Así, Kakihara consigue averiguar que lo que pensaban que era una desaparición, es en realidad un asesinato, cometido por un hombre llamado Ichi, un esquizofrénico que cuando pierde el control puede hacer picadillo, literalmente, a cualquiera. Con esto, quiere resarcirse de los traumas de la infancia, aunque lo que consigue es lo contrario. Pero Ichi no esta sólo en esta lucha, le acompañan unos repudiados del clan, destacando a Jijii, que es la cabeza del grupo y quien incita al caos que se organiza.",
        popularity: 17.974,
        poster_path: "/gtqkEgS7fhvgKmSCt9EqTdQt6t9.jpg",
        release_date: "2001-12-22",
        title: "Ichi the Killer",
        video: false,
        vote_average: 7,
        vote_count: 679,
      },
      {
        adult: false,
        backdrop_path: "/1KFHukSqkSRxsm2XStCAfNEksvK.jpg",
        genre_ids: [18],
        id: 417670,
        media_type: "movie",
        original_language: "it",
        original_title: "Loro 1",
        overview:
          'Biopic sobre el ex Primer ministro italiano y empresario Silvio Berlusconi, centrada en la figura de «Il Cavaliere» a partir del año 2000 y que narra una historia de ficción, a partir tanto de diversos eventos personales y políticos como de hechos "probables o inventados".  El 24 de abril se estrenó en Italia la primera parte de esta biografía, que se dividió en dos partes por su larga duración. La segunda se espera que se estrene en Italia el 10 de mayo de 2018.',
        popularity: 9.054,
        poster_path: "/tNwCi4k8TKcGtay2SvyxCbSZnLT.jpg",
        release_date: "2018-04-24",
        title: "Silvio (y los otros)",
        video: false,
        vote_average: 6.8,
        vote_count: 481,
      },
      {
        backdrop_path: "/gO5ZWlnabkjJtQBVmDonhzfRsKx.jpg",
        first_air_date: "2022-03-10",
        genre_ids: [16, 18, 35],
        id: 134581,
        media_type: "tv",
        name: "Kotaro vive solo",
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "コタローは1人暮らし",
        overview:
          "Kotarō Satо̄ es un niño de cuatro años que se mueve al apartamento de al lado de Shin Karino, un desafortunado dibujante de manga. Kotarō no tiene padres y vive solo. No sólo es capaz de ganarse la vida por cuenta propia, si no que además vive una vida más ordenada que sus extraños vecinos.",
        popularity: 26.081,
        poster_path: "/bR144FenQIvt5ugXxoNp6npnVts.jpg",
        vote_average: 6.8,
        vote_count: 5,
      },
      {
        adult: false,
        backdrop_path: "/sbqBNJyIRSkiVk7pJdLCUyHXae3.jpg",
        genre_ids: [18, 10749],
        id: 416691,
        media_type: "movie",
        original_language: "en",
        original_title: "1 Night",
        overview:
          "Bea (Isabelle Fuhrman), una adolescente preocupada, se reconecta con su introvertido amigo de la infancia, Andy (Kyle Allen). Los dos superan sus diferencias en el estatus social una noche después de su baile de graduación de secundaria. Mientras tanto, Elizabeth (Anna Camp) debe decidir si salvar su relación con Drew (Justin Chatwin) después de mucha decepción personal. Pasado y presente chocan cuando dos parejas exploran el amor en el transcurso de una noche en un hotel.",
        popularity: 9.039,
        poster_path: "/geYX4v0Jy3PvzFei8QL1educKxh.jpg",
        release_date: "2016-10-14",
        title: "1 Night",
        video: false,
        vote_average: 6.3,
        vote_count: 135,
      },
      {
        adult: false,
        backdrop_path: "/1f9kaPcMAHGZmy3F81Z0d041UXX.jpg",
        genre_ids: [37, 12],
        id: 3685,
        media_type: "movie",
        original_language: "de",
        original_title: "Winnetou 1",
        overview:
          "Una compañía planea la construcción de una línea ferroviaria que una el este y el oeste de Estados Unidos, pero los colonos y las tribus indias que habitan el territorio no están dispuestos a permitírselo. Los conflictos entre los afectados y la compañía se agravan cuando Santer, el líder de una banda de delincuentes, intenta saquear una mina de oro ubicada en territorio apache.",
        popularity: 7.38,
        poster_path: "/uPmDW5FNCmGzRYv8UTfRUE0bXKU.jpg",
        release_date: "1963-12-11",
        title: "Furia Apache",
        video: false,
        vote_average: 6.7,
        vote_count: 98,
      },
      {
        adult: false,
        backdrop_path: "/qCdQ74WI765kLOJBWKJ1qVamU42.jpg",
        genre_ids: [35, 878],
        id: 9805,
        media_type: "movie",
        original_language: "de",
        original_title: "(T)Raumschiff Surprise - Periode 1",
        overview:
          "Los tripulantes de la nave estelar Surprise son requeridos por el alto mando terrestre, liderado por la princesa Metapha, para viajar atrás en el tiempo y cambiar el pasado para así prevenir la invasión de las tropas marcianas del malvado Regulator Rogul y su sicario, el asmático Lord Jens Maul.",
        popularity: 15.428,
        poster_path: "/60YgMkDDwobP4JXwc2hOFa2VmGg.jpg",
        release_date: "2004-07-14",
        title: "Dreamship Surprise: Period 1",
        video: false,
        vote_average: 6.2,
        vote_count: 380,
      },
      {
        backdrop_path: "/hGobLu6lU6IWwUttvANsWGMGJQj.jpg",
        first_air_date: "2019-11-22",
        genre_ids: [],
        id: 104021,
        media_type: "tv",
        name: "Unexplained 9-1-1",
        origin_country: ["CA"],
        original_language: "en",
        original_name: "Unexplained 9-1-1",
        overview: "",
        popularity: 4.24,
        poster_path: "/4zfjQ9NBkRX9ZwIiqNmYNUmWVu5.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/dlq3GoejDFL1AfLeoOnarf6bGUW.jpg",
        genre_ids: [28, 35, 10749],
        id: 249772,
        media_type: "movie",
        original_language: "te",
        original_title: "1 - నేనొక్కడినే",
        overview: "",
        popularity: 4.931,
        poster_path: "/dYpqpA7BsDHeyAGs9AAEPhZmbck.jpg",
        release_date: "2014-01-10",
        title: "1 - నేనొక్కడినే",
        video: false,
        vote_average: 6.3,
        vote_count: 55,
      },
      {
        adult: false,
        backdrop_path: "/3Ywbn6XkpBBemuoThyUwr0opLmG.jpg",
        genre_ids: [28, 53, 80, 18],
        id: 15362,
        media_type: "movie",
        original_language: "fr",
        original_title: "L'ennemi public n°1",
        overview:
          'Nueva entrega sobre la vida de Jacques Mesrine entre 1973 y 1979, época en la que se le conoció como el enemigo público número 1. Todo comenzó cuando consiguió fugarse del tribunal de Compiègne, encañonando al juez hasta la calle, donde un compinche lo esperaba en un coche. La muerte de su padre, sus espectaculares atracos a sucursales bancarias, sus huidas trepidantes, o la publicación de su libro "L\'instinct de mort", desde la cárcel, son algunos de los hechos más destacables de su biografía.',
        popularity: 8.811,
        poster_path: "/AiL4pmpD6plmGUcmOZxCCXiu47B.jpg",
        release_date: "2008-11-19",
        title: "Mesrine Parte 2. Enemigo público nº1",
        video: false,
        vote_average: 7.4,
        vote_count: 692,
      },
      {
        adult: false,
        backdrop_path: "/gfxQJX7mWe008zs3OOsEAgAUfic.jpg",
        genre_ids: [18],
        id: 413576,
        media_type: "movie",
        original_language: "en",
        original_title: "1/1",
        overview:
          "Sin aliento, atrevido y deshecho en un millón de piezas. Al describir tanto el estilo como el personaje principal de la película, 1/1 sumerge a la audiencia en la mente de Lissa, una niña de veinte años atrapada en la zona rural de Pensilvania, que lidia con el sexo, las drogas, el amor y la pérdida. Cuando un posible embarazo fuerza a Lissa a mirar su vida con rigor, tanto ella como la estructura de la película maduran, iluminando un camino más brillante por delante.",
        popularity: 3.951,
        poster_path: "/hSr9f8ex7FIViB7Kg0HFJUl0qHN.jpg",
        release_date: "2018-07-07",
        title: "1/1",
        video: false,
        vote_average: 4.9,
        vote_count: 20,
      },
      {
        backdrop_path: "/deSSvVnRiZQSrUSBwPpT6m67aA1.jpg",
        first_air_date: "2012-01-05",
        genre_ids: [35],
        id: 48268,
        media_type: "tv",
        name: "1 Erkek 1 Kadın",
        origin_country: ["TR"],
        original_language: "tr",
        original_name: "1 Erkek 1 Kadın",
        overview: "",
        popularity: 2.771,
        poster_path: "/aL5MhgTj3zxLtN2chrvWmI36S8Y.jpg",
        vote_average: 7.6,
        vote_count: 5,
      },
      {
        adult: false,
        backdrop_path: "/6EEajmpS6SpUC1gPOGwnXsuI18u.jpg",
        genre_ids: [35, 80, 28],
        id: 9644,
        media_type: "movie",
        original_language: "en",
        original_title: "National Lampoon's Loaded Weapon 1",
        overview:
          'Un inconformista policía de Los Ángeles recibe como compañero a un veterano a punto de jubilarse. Ambos investigarán el asesinato de una compañera. Parodia del cine de acción, en concreto de las "buddy movies": películas alrededor de una pareja de policías con diferentes personalidades.',
        popularity: 12.889,
        poster_path: "/p9LVtAoZPw4oO66LK2qo45wkty.jpg",
        release_date: "1993-02-04",
        title: "Con el arma a punto",
        video: false,
        vote_average: 5.9,
        vote_count: 544,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 53, 18],
        id: 50373,
        media_type: "movie",
        original_language: "ja",
        original_title: "1-イチ-",
        overview: "",
        popularity: 3.861,
        poster_path: "/r23t756RZh44fpF5uFDwvQqWUM5.jpg",
        release_date: "2003-01-01",
        title: "1-イチ-",
        video: false,
        vote_average: 6,
        vote_count: 40,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [99],
        id: 32571,
        media_type: "movie",
        original_language: "xx",
        original_title: "Monkeyshines, No. 1",
        overview: "",
        popularity: 6.619,
        poster_path: "/a41Z3Owp1TsXcUlBCRhbb9eJjWW.jpg",
        release_date: "1890-11-21",
        title: "Monkeyshines, No. 1",
        video: false,
        vote_average: 5,
        vote_count: 78,
      },
      {
        adult: false,
        backdrop_path: "/qjfI1fWva5Ux8cABcCGmb93UYt0.jpg",
        genre_ids: [16, 28, 53],
        id: 357390,
        media_type: "movie",
        original_language: "ja",
        original_title: "亜人　第１部「衝動」",
        overview:
          "Los ajin no pueden morir. Aparecieron por primera vez en África durante un conflicto bélico, hace diecisiete años. A partir de entonces, más especímenes han ido apareciendo en la sociedad humana y, para fines experimentales, el gobierno recompensará generosamente a cualquiera que capture uno. Ajeno a ello, un estudiante de bachillerato se dispone a comenzar sus vacaciones de verano, incapaz de pensar que su vida está a punto de tomar un giro inesperado.  Película que adapta los primeros 6 capítulos de la serie.",
        popularity: 22.988,
        poster_path: "/6c2iQ7W0dQBiSodz7GXIFTZtMIA.jpg",
        release_date: "2015-11-27",
        title: "Ajin: Demi-Human - Compel",
        video: false,
        vote_average: 7.2,
        vote_count: 48,
      },
      {
        backdrop_path: "/iv64cPses1WatCn4GmymsvrjYqc.jpg",
        first_air_date: "2016-06-20",
        genre_ids: [18, 80],
        id: 67158,
        media_type: "tv",
        name: "1 Contra Todos",
        origin_country: ["BR"],
        original_language: "pt",
        original_name: "1 Contra Todos",
        overview:
          "La serie relata la história de Cadu (Julio Andrade), un honesto padre de família y abogado, que inesperadamente es enviado a prisión luego de haber sido injustamente condenado por tráfico de drogas. En este contexto, Cadu tiene que cambiar su carácter y personalidad, y asumir la identidad de un criminal con el objetivo de sobrevivir en un mundo de asesinos. Pero esta decisión cambiará para siempre su vida y la de su familia.",
        popularity: 5.004,
        poster_path: "/3o7f2Xjwl5hcoiioR9eGdD9ezHt.jpg",
        vote_average: 7.2,
        vote_count: 6,
      },
    ],
    page_3: [
      {
        adult: false,
        backdrop_path: "/uKFqdRcJ3Oe2qZscCLCZVKo1nml.jpg",
        genre_ids: [10749, 18],
        id: 152584,
        media_type: "movie",
        original_language: "fr",
        original_title: "La Vie d'Adèle - Chapitres 1 et 2",
        overview:
          'Adèle (Adèle Exarchopoulos) tiene quince años y sabe que lo normal es salir con chicos, pero tiene dudas sobre su sexualidad. Una noche conoce y se enamora inesperadamente de Emma (Léa Seydoux), una joven con el pelo azul. La atracción que despierta en ella una mujer que le muestra el camino del deseo y la madurez, hará que Adèle tenga que sufrir los juicios y prejuicios de familiares y amigos. Adaptación de la novela gráfica "Blue", de Julie Maroh.',
        popularity: 17.604,
        poster_path: "/en27JWtPoF2nsWPqFoI8lj3y66d.jpg",
        release_date: "2013-10-09",
        title: "La vida de Adèle",
        video: false,
        vote_average: 7.1,
        vote_count: 3811,
      },
      {
        backdrop_path: null,
        first_air_date: "1994-01-05",
        genre_ids: [80, 18],
        id: 26357,
        media_type: "tv",
        name: "99-1",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "99-1",
        overview: "",
        popularity: 3.613,
        poster_path: "/13SGmF34QWguhtPCkNAxMwBzCGZ.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/vV3BeSdFFLCLfpr78sS1a1jkOPP.jpg",
        genre_ids: [18, 10749],
        id: 342472,
        media_type: "movie",
        original_language: "en",
        original_title: "1 Mile To You",
        overview:
          "Después de que los amigos de un adolescente mueren en un accidente, descubre que correr le permite recordarlos perfectamente. Correr, sin embargo, también le da notoriedad. Está atrapado entre mantener vivo el pasado y hacer nuevos recuerdos en el presente.",
        popularity: 10.942,
        poster_path: "/by5sJxbg7HXdqSm05oYT54AsZTg.jpg",
        release_date: "2017-04-07",
        title: "Corazón de un Corredor",
        video: false,
        vote_average: 6.6,
        vote_count: 182,
      },
      {
        adult: false,
        backdrop_path: "/bNixlnIPYJCXFPo7voIVCaNCXa5.jpg",
        genre_ids: [35, 18],
        id: 614179,
        media_type: "movie",
        original_language: "hi",
        original_title: "Coolie No. 1",
        overview: "",
        popularity: 5.961,
        poster_path: "/5J2LiufXsOPAtO7ZiMBx0ksuoPu.jpg",
        release_date: "2020-12-25",
        title: "Coolie No. 1",
        video: false,
        vote_average: 5.9,
        vote_count: 44,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [],
        id: 945827,
        media_type: "movie",
        original_language: "ja",
        original_title: "Naruto Special 1: Find the Crimson Four-leaf Clover!",
        overview: "",
        popularity: 27.965,
        poster_path: "/wiKZYCSxh1ANV2akMI9o8Y6Br0D.jpg",
        release_date: "2003-05-24",
        title: "Naruto Special 1: Find the Crimson Four-leaf Clover!",
        video: false,
        vote_average: 2,
        vote_count: 1,
      },
      {
        backdrop_path: "/i6RqdM9RH8r7pvGxvtMJrzKL5RO.jpg",
        first_air_date: "1993-10-21",
        genre_ids: [16, 10759, 35],
        id: 152335,
        media_type: "tv",
        name: "Ranma ½ OVA",
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "らんま1/2 OVA",
        overview:
          "Ranma ½ es un manga y anime humorístico de Rumiko Takahashi el cual trata sobre un chico llamado Ranma Saotome, quien sufre una peculiar maldición desde que cayó en un estanque maldito durante un entrenamiento de artes marciales en China. Desde aquel día, cuando se moja con agua fría se convierte en una atractiva chica pelirroja, y al tener contacto con agua caliente vuelve a su estado original de chico.",
        popularity: 10.315,
        poster_path: "/8h0nrBoKsiXuPNTBQWej544hYrp.jpg",
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/5NrTEJfBJkKXVtn0aruyuH1rQ4.jpg",
        genre_ids: [16, 12, 878],
        id: 357400,
        media_type: "movie",
        original_language: "ja",
        original_title: "デジモンアドベンチャーtri.（トライ）第１章「再会」",
        overview:
          'Primera de las seis películas de la saga "Digimon Adventure tri", una secuela directa de la serie "Digimon". (FILMAFFINITY)  Estreno en Japón: 21 de noviembre de 2015.',
        popularity: 15.198,
        poster_path: "/hUB2K3u82VAOGyLTZjhh7XIRQZN.jpg",
        release_date: "2015-11-21",
        title: "Digimon Adventure tri. 1 Reunión",
        video: false,
        vote_average: 6.6,
        vote_count: 68,
      },
      {
        adult: false,
        backdrop_path: "/prqQoRgx1hiHokgqrqG2eGD1cOC.jpg",
        genre_ids: [18],
        id: 415665,
        media_type: "movie",
        original_language: "fr",
        original_title: "1:54",
        overview:
          "A sus 16 años, Tim es un joven tímido, brillante y con un talento deportivo natural. Víctima de acoso escolar e incapaz de aceptar su orientación sexual, plantará cara a sus acosadores tras un trágico suceso que marcará profundamente su vida y le empujará a desafiar sus propios límites.",
        popularity: 5.47,
        poster_path: "/8uHDTAHeIE5VebYNxLGarQ39GNm.jpg",
        release_date: "2016-10-13",
        title: "1:54",
        video: false,
        vote_average: 6.8,
        vote_count: 118,
      },
      {
        adult: false,
        backdrop_path: "/lgaLsjUmJaj9WX68tdHhNRLUyV3.jpg",
        genre_ids: [10770, 12, 35],
        id: 715869,
        media_type: "movie",
        original_language: "it",
        original_title: "Tutti per 1 - 1 per tutti",
        overview: "",
        popularity: 5.399,
        poster_path: "/8PBmNXkiSskH6VzJ4FcmMH06QxK.jpg",
        release_date: "2020-12-25",
        title: "Tutti per 1 - 1 per tutti",
        video: false,
        vote_average: 5.8,
        vote_count: 132,
      },
      {
        adult: false,
        backdrop_path: "/gZET2df3Ietn2kYEBZ9X5cVPKxi.jpg",
        genre_ids: [18, 9648],
        id: 94528,
        media_type: "movie",
        original_language: "fr",
        original_title: "Out 1",
        overview: "",
        popularity: 4.57,
        poster_path: "/9P2oLzm3XlrBmzcSPJ1wKrD5kS6.jpg",
        release_date: "1971-10-09",
        title: "Out 1",
        video: false,
        vote_average: 7.4,
        vote_count: 37,
      },
      {
        adult: false,
        backdrop_path: "/mouu6kAzrEuPFBCRU5NkPHM292v.jpg",
        genre_ids: [35],
        id: 41371,
        media_type: "movie",
        original_language: "en",
        original_title: "#1 Cheerleader Camp",
        overview: "",
        popularity: 7.257,
        poster_path: "/jnZ9RiTyusgR3D6QOhF7CAI44TK.jpg",
        release_date: "2010-07-27",
        title: "#1 Cheerleader Camp",
        video: false,
        vote_average: 4.6,
        vote_count: 72,
      },
      {
        backdrop_path: "/vxsoaSyPXJAjZmBAZQbTHRKoXwo.jpg",
        first_air_date: "2021-07-16",
        genre_ids: [99],
        id: 127907,
        media_type: "tv",
        name: "McCartney 3, 2, 1",
        origin_country: ["US"],
        original_language: "en",
        original_name: "McCartney 3, 2, 1",
        overview:
          "Paul McCartney se sienta para un inusual y profundo uno a uno con Rick Rubin para discutir su innovador trabajo con The Beatles, el emblemático rock de de estadio de Wings en los 70’s, y sus 50 años (y contando) como solista, en esta serie de seis episodios que explora la música y la creatividad de una manera única y reveladora. Únete a Paul y Rick para una conversación íntima sobre la maestría musical, la composición de canciones, el ingenio, las influencias y las relaciones personales reveladas por las icónicas canciones que han servido como banda sonora de nuestras vidas.",
        popularity: 5.728,
        poster_path: "/oFLsac8ieC0qCjucFosdbgxpXkm.jpg",
        vote_average: 9.2,
        vote_count: 11,
      },
      {
        adult: false,
        backdrop_path: "/esSip792iOHaXHBJNLPeyQOxWsz.jpg",
        genre_ids: [18, 53],
        id: 477201,
        media_type: "movie",
        original_language: "en",
        original_title: "1 Buck",
        overview: "",
        popularity: 5.151,
        poster_path: "/tDiAfxcjz5bydpbqTtBYBfaYHKD.jpg",
        release_date: "2017-09-22",
        title: "1 Buck",
        video: false,
        vote_average: 5.9,
        vote_count: 52,
      },
      {
        adult: false,
        backdrop_path: "/8a8BeADyD8AIOFmSI9N7a8Dbrjl.jpg",
        genre_ids: [18],
        id: 825206,
        media_type: "movie",
        original_language: "zh",
        original_title: "JAOfilm No. 1",
        overview: "",
        popularity: 5.809,
        poster_path: "/wLDAhz3BsAygaBvoIe6RifrFZRp.jpg",
        release_date: "2019-06-01",
        title: "JAOfilm No. 1",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/x3KbliX22O075Og3aNyeuybRJfy.jpg",
        genre_ids: [28, 18],
        id: 882670,
        media_type: "movie",
        original_language: "en",
        original_title: "WWE Day 1 2022",
        overview:
          "WWE comienza 2022 con el primer evento del Día 1. Big E pone en juego el Campeonato de la WWE contra Brock Lesnar, Seth Rollins, Kevin Owens y Bobby Lashley en un Fatal 5-Way Match. Becky Lynch defiende el título femenino de Raw ante Liv Morgan.",
        popularity: 9.263,
        poster_path: "/vumyRztyLMEvYYjyzONNy0SeFxF.jpg",
        release_date: "2022-01-01",
        title: "WWE Day 1 2022",
        video: true,
        vote_average: 7.2,
        vote_count: 124,
      },
      {
        backdrop_path: null,
        first_air_date: "1990-02-23",
        genre_ids: [16, 35],
        id: 44230,
        media_type: "tv",
        name: "1+2=Paradise",
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "１＋２＝パラダイス",
        overview:
          "Se desarrolla una extraña relación entre el universitario Yusuke y los hermosos gemelos, Yuika y Rika, que salva de un perro salvaje. Las chicas se enamoran de su intrépido héroe, pero Yusuke tiene un miedo patológico a las mujeres.",
        popularity: 3.333,
        poster_path: "/yN5r8lRwjgI3DEaRCCbpuxNJ5pg.jpg",
        vote_average: 4.4,
        vote_count: 7,
      },
      {
        adult: false,
        backdrop_path: "/kBWPHSszi8jKLqW5tMaQV1bISB2.jpg",
        genre_ids: [53, 80, 28],
        id: 18487,
        media_type: "movie",
        original_language: "en",
        original_title: "The Taking of Pelham 1 2 3",
        overview:
          "Walter Garber, supervisor del metro de Nueva York, tiene que afrontar el caos provocado por el secuestro de un vagón por una banda armada. Los criminales amenazan con ejecutar a los pasajeros si en una hora no reciben un cuantioso rescate. Garber utiliza sus conocimientos del sistema suburbano para intentar burlar a Ryder y salvar a los rehenes. Pero hay un enigma que Garber no consigue resolver: en el caso de que los criminales obtuvieran el dinero, ¿cómo conseguirían escapar? Remake de 'Pelham uno, dos, tres' (1974).",
        popularity: 16.71,
        poster_path: "/lm16bCPiOY24TNqnCFBfB8YkF38.jpg",
        release_date: "2009-06-10",
        title: "Asalto al tren Pelham 123",
        video: false,
        vote_average: 6.3,
        vote_count: 2555,
      },
      {
        adult: false,
        gender: 0,
        id: 89137,
        known_for: [
          {
            adult: false,
            genre_ids: [10402],
            id: 22703,
            media_type: "movie",
            original_language: "en",
            original_title: "Sensation 2001",
            overview: "",
            release_date: "2001-07-07",
            title: "Sensation 2001",
            video: true,
            vote_average: 4.3,
            vote_count: 2,
          },
        ],
        known_for_department: "Acting",
        media_type: "person",
        name: "Rank 1",
        popularity: 0.6,
        profile_path: null,
      },
      {
        adult: false,
        gender: 0,
        id: 2109877,
        known_for: [
          {
            backdrop_path: "/ieiavvajx8DaZfTcOOOimsIdbWv.jpg",
            first_air_date: "2017-05-21",
            genre_ids: [10763, 10767],
            id: 73232,
            media_type: "tv",
            name: "Le beau dimanche",
            origin_country: ["CA"],
            original_language: "fr",
            original_name: "Le beau dimanche",
            overview: "",
            poster_path: "/9C6oAJCFsJwmnAJN81VWDJAGnrV.jpg",
            vote_average: 9,
            vote_count: 1,
          },
        ],
        known_for_department: "Acting",
        media_type: "person",
        name: "Dave 1",
        popularity: 0.6,
        profile_path: null,
      },
      {
        adult: false,
        gender: 0,
        id: 3341528,
        known_for: [
          {
            adult: false,
            backdrop_path: "/pUlc0VkIRNjGQSgHEhKSGpOcRKl.jpg",
            genre_ids: [878],
            id: 913456,
            media_type: "movie",
            original_language: "ml",
            original_title: "REPLICA",
            overview: "",
            poster_path: "/bS7iANNhhoV0YfkRd4BkuvbFNx2.jpg",
            release_date: "2020-07-07",
            title: "REPLICA",
            video: false,
            vote_average: 10,
            vote_count: 1,
          },
        ],
        known_for_department: "Acting",
        media_type: "person",
        name: "Rabbit 1",
        popularity: 0.6,
        profile_path: null,
      },
    ],
  },
};
