name: Deploy

on:
  push:
    branches: [master]
env:
  VITE_OMDB_API_KEY: ae63f570
  VITE_TMDB_API_KEY: 5cbcf6f5d3e8e12a4226fd2675b7efbb

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install and build
        run: |
          yarn install
          yarn build
      - name: Deploy process
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
