name: push to master

on:
  push:
    branches:
      - dev

jobs:
  set_up:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install, build & preview
        run: |
          yarn ci
          yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  vitest_test:
    needs: set_up
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn ci
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Test
        run: yarn vitest:run

  cypress_test:
    needs: set_up
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn ci
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: E2E test
        uses: cypress-io/github-action@v4
        with:
          command: yarn cy:run
          start: yarn preview
          wait-on: http://localhost:4173
