name: push to master

on:
  push:
    branches: [dev]

jobs:
  set_up:
    runs-on: ubuntu-22.04
    env:
      VITE_TMDB_API_KEY: ${{ secrets.TMDB }}
    steps:
      - shell: bash

        run: |
          echo "$VITE_TMDB_API_KEY"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn ci
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
